name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: "8.x"


jobs:
  build:
    runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: ${{ env.DOTNET_VERSION }}
        
        - name: Restore
          run: dotnet restore ./DotnetDemo.sln
        
        - name: Build
          run: dotnet build ./DotnetDemo.sln --configuration Release --no-restore
        
        # - name: Test
        #   run: dotnet test ./DotnetDemo.sln --configuration Release --no-restore
  
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Dockerhub
        uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .
          tags: vgoyal/dotnetdemo:latest
      